name: Website

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build docs
        run: |
          pnpm run docs:build
          touch ./docs/dist/.nojekyll

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: true
          branch: gh-pages
          folder: ./docs/dist
          token: ${{secrets.ACCESS_TOKEN}}
